name: Test Python Environment

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  test-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Check requirements files
      run: |
        echo 'Checking requirements files...'
        if [ -f requirements.txt ]; then
          echo ' requirements.txt exists'
        else
          echo ' requirements.txt does not exist'
        fi
        if [ -f requirements-ci.txt ]; then
          echo ' requirements-ci.txt exists'
          cat requirements-ci.txt
        else
          echo ' requirements-ci.txt does not exist'
        fi
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install CPU-only PyTorch to save disk space (much smaller than CUDA version)
        pip install torch==2.8.0+cpu torchaudio==2.8.0+cpu --index-url https://download.pytorch.org/whl/cpu
        # Install other dependencies
        pip install -r requirements-ci.txt
        
    - name: Create necessary directories
      run: |
        mkdir -p data/audio data/transcripts data/summaries data/embeddings logs
        
    - name: Debug environment
      run: |
        echo 'Current directory: $(pwd)'
        echo 'Files in directory:'
        ls -la
        echo 'Python version:'
        python --version
        echo 'Pip list:'
        pip list
        
    - name: Minimal Python test
      run: |
        python minimal_test.py
        
    - name: Simple Python test
      run: |
        python simple_test.py
        
    - name: Test basic functionality
      run: |
        python test_github_actions.py
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SUBSCRIBER_EMAILS: ${{ secrets.SUBSCRIBER_EMAILS }}
        EMAIL_ENABLED: true
        DATABASE_URL: sqlite:///data/db.sqlite
